FLT_MAX requires include <cfloat>
Fixes error: 'FLT_MAX' was not declared in this scope.
Tested on gcc 4.7 on armv7 & gcc 4.9 on x64

Signed-off-by: Matthieu Crapet <mcrapet@gmail.com>